#include <stdio.h>
#include <stdlib.h>
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "ws2812.pio.h"

#define IS_RGBW true        // Will use RGBW format
#define NUM_PIXELS 1        // There is 1 WS2812 device in the chain
#define WS2812_PIN 28       // The GPIO pin that the WS2812 connected to

int CURR_LIVES = 3;         // Current lives the player has
int LOST_LIVES = 0;         // Records the number of lives the player has lost
int GAINED_LIVES = 0;       // Records the number of lives the player has gained

/**
 * @brief Wrapper function used to call the underlying PIO
 *        function that pushes the 32-bit RGB colour value
 *        out to the LED serially using the PIO0 block. The
 *        function does not return until all of the data has
 *        been written out.
 * 
 * @param pixel_grb The 32-bit colour value generated by urgb_u32()
 */
static inline void put_pixel(uint32_t pixel_grb) {
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}
/**
 * @brief Function to generate an unsigned 32-bit composit GRB
 *        value by combining the individual 8-bit paramaters for
 *        red, green and blue together in the right order.
 * 
 * @param r     The 8-bit intensity value for the red component
 * @param g     The 8-bit intensity value for the green component
 * @param b     The 8-bit intensity value for the blue component
 * @return uint32_t Returns the resulting composit 32-bit RGB value
 */

static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return  ((uint32_t) (r) << 8)  |
            ((uint32_t) (g) << 16) |
            (uint32_t) (b);
}

// Function that displays Red Blue or Green depending on how many lives the player has left
void RGB_display(int lives)
{
    switch (lives)
    {
        case 0:
            // Set the colors off
            put_pixel(urgb_u32(0x00, 0x00, 0x00));
            printf("No lives remain, you lose\n");
            break;
        case 1:
            // Set the color to red at half intensity
            put_pixel(urgb_u32(0x7F, 0x00, 0x00));
            printf("1 life remaining\n");
            break;
        case 2:
            // Set the color to blue at half intensity
            put_pixel(urgb_u32(0x00, 0x00, 0x7F));
            printf("2 lives remaining\n");
            break;
        case 3:
            // Set the color to green at half intensity
            put_pixel(urgb_u32(0x00, 0x7F, 0x00));
            printf("3 lives remaining\n");
            break;
        default:
            printf("Invalid lives, something went wrong\n");
            break;
    }

}

// Updates the player's lives based on whether or not they answered a sequence correctly
void update_lives(bool answer)
{
    if (answer)
    {
        printf("Correct! Adding a life.\n");
        GAINED_LIVES ++;
        if (CURR_LIVES == 3)
        {
            printf("You already have the maximum amount of lives, no more may be added.\n");
        }
        else
        {
            CURR_LIVES += 1;
            RGB_display(CURR_LIVES);
        }
    }
    else
    {
        printf("Wrong! Taking away a life.\n");
        LOST_LIVES ++;
        CURR_LIVES -= 1;
        RGB_display(CURR_LIVES);
    }
}


// Print a welcome message for the user
void welcome_message()
{
    printf("+---------------------------------------------------------+\n");
    printf(":                    Group 5 Presents                     :\n");
    printf("+---------------------------------------------------------+\n");
    printf(":      #       #######     #    ######   #      #         :\n");
    printf(":      #       #          # #   #    #   # #    #         :\n");
    printf(":      #       #         #   #  #    #   #  #   #         :\n");
    printf(":      #       #######  ######  ######   #   #  #         :\n");
    printf(":      #       #        #    #  #  #     #    # #         :\n");
    printf(":      #       #        #    #  #   #    #     ##         :\n");
    printf(":      ####### #######  #    #  #    #   #      #         :\n");
    printf(":                                                         :\n");
    printf(":    #        #    #######    ######    #####   ######    :\n");
    printf(":    # #    # #   #       #   #     #  #     #  #         :\n");
    printf(":    #   # #  #   #       #   #     #  #        #         :\n");
    printf(":    #    #   #   #       #   ######    #####   #####     :\n");
    printf(":    #        #   #       #   #  #           #  #         :\n");
    printf(":    #        #   #       #   #   #    #     #  #         :\n");
    printf(":    #        #    ########   #    #   ######   ######    :\n");
    printf(":                                                         :\n");
    printf(":             ######   #######   #####     ######         :\n");
    printf(":           ##        #       #  #    #    #              :\n");
    printf(":          ##         #       #  #     #   #              :\n");
    printf(":          ##         #       #  #     #   #####          :\n");
    printf(":          ##         #       #  #     #   #              :\n");
    printf(":           ##        #       #  #    #    #              :\n");
    printf(":            #######   ########  ####      ######         :\n");
    printf("+---------------------------------------------------------+\n");
}


// Must declare the main assembly entry point before use.
void main_asm();

// Initialise a GPIO pin
void asm_gpio_init(uint pin) {
    gpio_init(pin);
}

// Set direction of a GPIO pin
void asm_gpio_set_dir(uint pin, bool out) {
    gpio_set_dir(pin, out);
}

// Get the value of a GPIO pin
bool asm_gpio_get(uint pin) {
    return gpio_get(pin);
}

// Set the value of a GPIO pin 
void asm_gpio_put(uint pin, bool value) {
    gpio_put(pin, value);
}

// Enable falling-edge interrupt 
void asm_gpio_set_irq_fall(uint pin) {
    gpio_set_irq_enabled(pin, GPIO_IRQ_EDGE_FALL, true);
}

// Enable rising-edge interrupt
void asm_gpio_set_irq_rise(uint pin) {
    gpio_set_irq_enabled(pin, GPIO_IRQ_EDGE_RISE, true);
}


/*
 * Main entry point for the code - simply calls the main assembly function.
 */
int main() {

    // Initialise all STDIO as we will be using the GPIOs
    stdio_init_all();
 
    // Initialise the PIO interface with the WS2812 code
    PIO pio = pio0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, 0, offset, WS2812_PIN, 800000, IS_RGBW);

    main_asm();
    return(0);
}
