
#include <stdio.h>
#include <stdlib.h>
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "ws2812.pio.h"

#define IS_RGBW true        // Will use RGBW format
#define NUM_PIXELS 1        // There is 1 WS2812 device in the chain
#define WS2812_PIN 28       // The GPIO pin that the WS2812 connected to

int CURR_LIVES = 3;         // Current lives the player has
int LOST_LIVES = 0;         // Records the number of lives the player has lost
int GAINED_LIVES = 0;       // Records the number of lives the player has gained
int CORRECT_ANSWERS = 0;    // records the number of correct answers in a row

/**
 * @brief Wrapper function used to call the underlying PIO
 *        function that pushes the 32-bit RGB colour value
 *        out to the LED serially using the PIO0 block. The
 *        function does not return until all of the data has
 *        been written out.
 * 
 * @param pixel_grb The 32-bit colour value generated by urgb_u32()
 */
static inline void put_pixel(uint32_t pixel_grb) {
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}
/**
 * @brief Function to generate an unsigned 32-bit composit GRB
 *        value by combining the individual 8-bit paramaters for
 *        red, green and blue together in the right order.
 * 
 * @param r     The 8-bit intensity value for the red component
 * @param g     The 8-bit intensity value for the green component
 * @param b     The 8-bit intensity value for the blue component
 * @return uint32_t Returns the resulting composit 32-bit RGB value
 */
#define  ALPHABET_SIZE  36

typedef struct morse {
  char letter;
  char * code;
  int  sequence;
} morse;

morse alphabet[ALPHABET_SIZE];


void morse_init (){
    
    
    alphabet[0].letter='A';
    alphabet[1].letter='B';
    alphabet[2].letter='C';
    alphabet[3].letter='D';
    alphabet[4].letter='E';
    alphabet[5].letter='F';
    alphabet[6].letter='G';
    alphabet[7].letter='H';
    alphabet[8].letter='I';
    alphabet[9].letter='J';
    alphabet[10].letter='K';
    alphabet[11].letter='L';
    alphabet[12].letter='M';
    alphabet[13].letter='N';
    alphabet[14].letter='O';
    alphabet[15].letter='P';
    alphabet[16].letter='Q';
    alphabet[17].letter='R';
    alphabet[18].letter='S';
    alphabet[19].letter='T';
    alphabet[20].letter='U';
    alphabet[21].letter='V';
    alphabet[22].letter='W';
    alphabet[23].letter='X';
    alphabet[24].letter='Y';
    alphabet[25].letter='Z';
    alphabet[26].letter='0';
    alphabet[27].letter='1';
    alphabet[28].letter='2';
    alphabet[29].letter='3';
    alphabet[30].letter='4';
    alphabet[31].letter='5';
    alphabet[32].letter='6';
    alphabet[33].letter='7';
    alphabet[34].letter='8';
    alphabet[35].letter='9';

    alphabet[0].code=".-";
    alphabet[1].code="-...";
    alphabet[2].code="-.-.";
    alphabet[3].code="-..";
    alphabet[4].code=".";
    alphabet[5].code="..-.";
    alphabet[6].code="--.";
    alphabet[7].code="....";
    alphabet[8].code="..";
    alphabet[9].code=".---";
    alphabet[10].code="-.-";
    alphabet[11].code=".-..";
    alphabet[12].code="--";
    alphabet[13].code="-.";
    alphabet[14].code="---";
    alphabet[15].code=".--.";
    alphabet[16].code="--.-";
    alphabet[17].code=".-.";
    alphabet[18].code="...";
    alphabet[19].code="-";
    alphabet[20].code="..-";
    alphabet[21].code="...-";
    alphabet[22].code=".--";
    alphabet[23].code="-..-";
    alphabet[24].code="-.--";
    alphabet[25].code="--..";
    alphabet[26].code="-----";
    alphabet[27].code=".----";
    alphabet[28].code="..---";
    alphabet[29].code="...--";
    alphabet[30].code="....-";
    alphabet[31].code=".....";
    alphabet[32].code="-....";
    alphabet[33].code="--...";
    alphabet[34].code="---..";
    alphabet[35].code="----.";

    alphabet[0].sequence=15;
    alphabet[1].sequence=3657;
    alphabet[2].sequence=3705;
    alphabet[3].sequence=457;
    alphabet[4].sequence=1;
    alphabet[5].sequence=633;
    alphabet[6].sequence=505;
    alphabet[7].sequence=585;
    alphabet[8].sequence=9;
    alphabet[9].sequence=1023;
    alphabet[10].sequence=463;
    alphabet[11].sequence=969;
    alphabet[12].sequence=63;
    alphabet[13].sequence=57;
    alphabet[14].sequence=511;
    alphabet[15].sequence=1017;
    alphabet[16].sequence=4047;
    alphabet[17].sequence=121;
    alphabet[18].sequence=73;
    alphabet[19].sequence=7;
    alphabet[20].sequence=79;
    alphabet[21].sequence=591;
    alphabet[22].sequence=127;
    alphabet[23].sequence=3663;
    alphabet[24].sequence=3711;
    alphabet[25].sequence=4041;
    alphabet[26].sequence=32767;
    alphabet[27].sequence=8191;
    alphabet[28].sequence=5119;
    alphabet[29].sequence=4735;
    alphabet[30].sequence=4687;
    alphabet[31].sequence=4681;
    alphabet[32].sequence=29257;
    alphabet[33].sequence=32329;
    alphabet[34].sequence=32713;
    alphabet[35].sequence=32761;

    return;
}


static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return  ((uint32_t) (r) << 8)  |
            ((uint32_t) (g) << 16) |
            (uint32_t) (b);
}

// Function that displays Red Blue or Green depending on how many lives the player has left
void RGB_display(int lives)
{
    switch (lives)
    {
        case 0:
            // Set the colors off
            put_pixel(urgb_u32(0x00, 0x00, 0x00));
            printf("No lives remain, you lose\n");
            break;
        case 1:
            // Set the color to red at half intensity
            put_pixel(urgb_u32(0x7F, 0x00, 0x00));
            printf("1 life remaining\n");
            break;
        case 2:
            // Set the color to blue at half intensity
            put_pixel(urgb_u32(0x00, 0x00, 0x7F));
            printf("2 lives remaining\n");
            break;
        case 3:
            // Set the color to green at half intensity
            put_pixel(urgb_u32(0x00, 0x7F, 0x00));
            printf("3 lives remaining\n");
            break;
        default:
            printf("Invalid lives, something went wrong\n");
            break;
    }

}

void RGB_display_welcome(){
    put_pixel(urgb_u32(0x00, 0x00, 0x7F)); //set led blue
}
int random_number=0;
int input=-1;

int32_t check (int32_t sequence){
  int answer=-1;
    for (int i=0; i<ALPHABET_SIZE;i++){   //identifying 
        if (alphabet[i].sequence==sequence){
            answer= sequence;
           
        }
      //  answer=alphabet[i].sequence;
    }
 
    return answer;

}


void lives_init(){
    CURR_LIVES = 3;         // Current lives the player has
    LOST_LIVES = 0;         // Records the number of lives the player has lost
    GAINED_LIVES = 0;       // Records the number of lives the player has gained
    CORRECT_ANSWERS = 0;    // records the number of correct answers in a row
    RGB_display(CURR_LIVES);
    return;
}

// Updates the player's lives based on whether or not they answered a sequence correctly
int32_t update_lives(int32_t sequence)
{
    int answer =0; 
    int inputIndex=-1;

    for (int i=0; i<ALPHABET_SIZE;i++){   //identifying 
        if (alphabet[i].sequence==sequence){
            inputIndex= i;
           
        }
      //  answer=alphabet[i].sequence;
    }
    if (random_number==inputIndex){
        answer=1;
    }
    
    if (answer)
    {
        printf("+---------------------------------------------------------+\n");
        printf(":                 Correct! Adding a life.                 :\n");
        printf("+---------------------------------------------------------+\n");
    
        GAINED_LIVES ++;
        CORRECT_ANSWERS ++;
        if (CURR_LIVES == 3)
        {
        printf("+---------------------------------------------------------+\n");
        printf(":     You already have the maximum amount of lives        :\n");
        printf("+---------------------------------------------------------+\n");
        
        }
        else
        {
            CURR_LIVES += 1;
            RGB_display(CURR_LIVES);
        }
    }
    else
    {
        if (inputIndex==-1){
            printf("+---------------------------------------------------------+\n");
            printf(":               Wrong! Taking away a life.                :\n");
            printf(":                      You Entered                        :\n");
            printf(":                           ?                             :\n");
            printf("+---------------------------------------------------------+\n");

        }
        else {
            printf("+---------------------------------------------------------+\n");
            printf(":               Wrong! Taking away a life.                :\n");
            printf(":                      You Entered                        :\n");
            printf(":                          %c %s                      \n",alphabet[inputIndex].letter,alphabet[inputIndex].code);
            printf("+---------------------------------------------------------+\n");
        }
        CORRECT_ANSWERS--;
        LOST_LIVES ++;
        CURR_LIVES -= 1;
        RGB_display(CURR_LIVES);
    }
    return CURR_LIVES;
}

void mistake (){
    printf("+---------------------------------------------------------+\n");
    printf(":                   Invalid Try again                     :\n");
    printf("+---------------------------------------------------------+\n");
}


void stat_init(){
    

}

void stat_print(){
    int accuracy= 100*(GAINED_LIVES/(GAINED_LIVES+LOST_LIVES));
    printf("+---------------------------------------------------------+\n");
    printf(":          In this level these were your stats            :\n");
    printf(":          Number of Letters attempted: %i                :\n",(GAINED_LIVES+LOST_LIVES));
    printf(":          Number of wrong answers:  %i                   :\n",LOST_LIVES);
    printf(":          Number of correct answers in total:  %i        :\n",GAINED_LIVES);
    printf(":               Accuracy:  %i percent                     :\n",accuracy);
    printf(":               Starting next level                       :\n");
    printf("+---------------------------------------------------------+\n");
    return;

}
bool still_alive() {
    if (CURR_LIVES>=0){
        return 0;
    }
    return 1;
}

bool level_sucess() {
    if (CORRECT_ANSWERS>=5){
        return 1;
    }
    return 0;
}

void status (){  // prints stats

}

void level_1_display(){
    random_number=rand()%36;
    printf("+---------------------------------------------------------+\n");
    printf(":       Reproduce this character in morse sequence        \n");
    printf(":                           %c                            \n",alphabet[random_number].letter);
    printf(":                          %s                            \n",alphabet[random_number].code);
    printf("+---------------------------------------------------------+\n");
    
}


void level_2_display(){
    random_number=rand()%36;
    printf("+---------------------------------------------------------+\n");
    printf(":             What is this in morse code?              \n");
    printf(":                           %c                            \n",alphabet[random_number].letter);
    printf("+---------------------------------------------------------+\n");
    
}

int16_t death_display(){
    if (CURR_LIVES>=0){
        return 0;
    }
    return 1;

}

void won(){
    printf("+---------------------------------------------------------+\n");
    printf(":                                                         :\n");
    printf(":                Material Girl You Won!!!!                :\n");
    printf(":                                                         :\n");
    printf("+---------------------------------------------------------+\n");


}

// Print a welcome message for the user
void welcome_message()
{
    printf("+---------------------------------------------------------+\n");
    printf(":                    Group 5 Presents                     :\n");
    printf("+---------------------------------------------------------+\n");
    printf(":      #       #######     #    ######   #      #         :\n");
    printf(":      #       #          # #   #    #   # #    #         :\n");
    printf(":      #       #         #   #  #    #   #  #   #         :\n");
    printf(":      #       #######  ######  ######   #   #  #         :\n");
    printf(":      #       #        #    #  #  #     #    # #         :\n");
    printf(":      #       #        #    #  #   #    #     ##         :\n");
    printf(":      ####### #######  #    #  #    #   #      #         :\n");
    printf(":                                                         :\n");
    printf(":    #        #    #######    ######    #####   ######    :\n");
    printf(":    # #    # #   #       #   #     #  #     #  #         :\n");
    printf(":    #   # #  #   #       #   #     #  #        #         :\n");
    printf(":    #    #   #   #       #   ######    #####   #####     :\n");
    printf(":    #        #   #       #   #  #           #  #         :\n");
    printf(":    #        #   #       #   #   #    #     #  #         :\n");
    printf(":    #        #    ########   #    #   ######   ######    :\n");
    printf(":                                                         :\n");
    printf(":             ######   #######   #####     ######         :\n");
    printf(":           ##        #       #  #    #    #              :\n");
    printf(":          ##         #       #  #     #   #              :\n");
    printf(":          ##         #       #  #     #   #####          :\n");
    printf(":          ##         #       #  #     #   #              :\n");
    printf(":           ##        #       #  #    #    #              :\n");
    printf(":            #######   ########  ####      ######         :\n");
    printf("+---------------------------------------------------------+\n");
    printf(":      Select Level by entering the correct sequence      :\n");
    printf(":           Level 1 =.----        Level 2=..---           :\n");
  

}




// Must declare the main assembly entry point before use.
void main_asm();

// Initialise a GPIO pin
void asm_gpio_init(uint pin) {
    gpio_init(pin);
}

// Set direction of a GPIO pin
void asm_gpio_set_dir(uint pin, bool out) {
    gpio_set_dir(pin, out);
}

// Get the value of a GPIO pin
bool asm_gpio_get(uint pin) {
    return gpio_get(pin);
}

// Set the value of a GPIO pin 
void asm_gpio_put(uint pin, bool value) {
    gpio_put(pin, value);
}

// Enable falling and rising edge interrupt 
void asm_gpio_set_irq_fall(uint pin) {
    gpio_set_irq_enabled(pin, GPIO_IRQ_EDGE_FALL, true);
    gpio_set_irq_enabled(pin, GPIO_IRQ_EDGE_RISE, true);
}

void word_detection(){
    

}

void dot_or_dash (){



}

void binary_tree_init () {


}



 //* Main entry point for the code - simply calls the main assembly function.

int main() {

    // Initialise all STDIO as we will be using the GPIOs
    stdio_init_all();
 
    // Initialise the PIO interface with the WS2812 code
    PIO pio = pio0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, 0, offset, WS2812_PIN, 800000, IS_RGBW);

    main_asm();
    return(0);
}
